型の変更とそれに伴う軽微な修正
tomoya0318/Board pull request #7
Opened 2024-10-07 08:40 UTC by tomoya0318

**やったこと**
- 型の名前の変更
- mapして値を画面に出力していたため，keyを使用するように変更

2024-10-09 17:01 UTC, Taiki-sub requested changes

2024-10-09 17:01 UTC, Taiki-sub commented on frontend/src/app/board/_components/ColumnItem.tsx
> +import { Item } from "@/types/board";
めっちゃ細かいけど、ここだけダブルクォーテーションになってる

2024-10-10 06:51 UTC, tomoya0318 commented on frontend/src/app/board/_components/ColumnItem.tsx
> +import { Item } from "@/types/board";
ダブルクォートに統一した

2024-10-10 07:24 UTC, Taiki-sub approved these changes

2024-10-10 13:50 UTC, merged